name: AMAI Build CI
on:
  push:
    branches: [ "master" ]
jobs:
  amai:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.30'
        distribution: strawberry
    - run: perl -V    
    - run: ./MakeTFT.bat
    - run: ./MakeOptTFT.bat
    - run: ./MakeVAITFT.bat
  analyse_logs_from_previous_steps:
      runs-on: ubuntu-latest
      needs: [amai] # necessary to wait for the previous jobs to be completed
      if: ${{ always() }} # necessary for the step to run with previous run failed.
      steps:
        - name: analyse_logs_from_previous_steps
          id: analyse_logs_from_previous_steps
          if: always() # necessary for the step to run with previous run failed.
          uses: Superbasil3/build-failure-analyser-action@main
          with:
            #github-token: ${{ secrets.GITHUB_TOKEN }}
            regexes-file-location: URL_CAUSES_FILE
